# Generated by Django 4.2.6 on 2023-10-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('category', models.CharField(choices=[('Фрукт', 'Fruits'), ('Овощи', 'Vegetables'), ('Мясо', 'Meat')], max_length=150, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/recipes_pictures', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание приготовления')),
                ('difficulty', models.CharField(choices=[('Сложно', 'Hard'), ('Средняя', 'Medium'), ('Легко', 'Easy')], max_length=50, verbose_name='Сложность')),
                ('cookingTime', models.TimeField(verbose_name='Время приготовления')),
                ('likesCount', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('commentsCount', models.IntegerField(default=0, verbose_name='Количество комментариев')),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/selection_pictures', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('recipes', models.ManyToManyField(related_name='recipes', to='recipes.recipe')),
            ],
        ),
    ]
