# Generated by Django 4.2.6 on 2023-10-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipes_pictures', verbose_name='Фото'),
        ),
    ]
