# Generated by Django 4.2.6 on 2023-11-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_commentrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentrecipe',
            old_name='autor',
            new_name='author',
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/recipes_pictures/steps', verbose_name='Фото шага')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание шага')),
                ('step_number', models.IntegerField(verbose_name='Номер шага')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
