# Generated by Django 4.2.6 on 2023-11-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_commentrecipe_author_ingredientquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
