# Generated by Django 4.2.6 on 2023-11-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_quentity_ingredientquantity_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='commentsCount',
        ),
    ]
