# Generated by Django 4.2.6 on 2023-11-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_commentscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookingTime',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
    ]
