# Generated by Django 4.2.6 on 2023-12-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_access_selection_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='access',
            field=models.CharField(choices=[('public', 'Общедоступный'), ('private', 'Закрытый')], default='private', max_length=10, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='access',
            field=models.CharField(choices=[('public', 'Общедоступный'), ('private', 'Закрытый')], default='private', max_length=10, verbose_name='Доступ'),
        ),
    ]
