# Generated by Django 4.2.6 on 2023-12-13 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0016_alter_recipe_access_alter_selection_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_selection', to='recipes.selection', verbose_name='Подборка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненная подборка',
                'verbose_name_plural': 'Сохраненные подборки',
                'ordering': ('-time_create',),
                'indexes': [models.Index(fields=['-time_create'], name='recipes_sav_time_cr_2a486c_idx')],
                'unique_together': {('selection', 'user')},
            },
        ),
    ]
