# Generated by Django 4.2.6 on 2023-12-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/ProfileIcon.png', null=True, upload_to='images/avatars/', verbose_name='avatar'),
        ),
    ]
