# Generated by Django 4.2.6 on 2023-12-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='', max_length=114, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Male'), ('Женский', 'Female')], max_length=20, null=True, verbose_name='Пол'),
        ),
    ]
