# Generated by Django 4.2.6 on 2023-12-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_birth_date_customuser_description_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='birth_date',
        # ),
    ]
