# Generated by Django 4.2.6 on 2023-12-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_birth_date'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='customuser',
        #     name='birth_date',
        #     field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        # ),
    ]
