# Generated by Django 4.2.6 on 2023-12-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_birth_date'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='customuser',
        #     old_name='birth_date',
        #     new_name='birth_dateee',
        # ),
    ]
