# Generated by Django 4.2.6 on 2023-12-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_birth_datee_customuser_birth_date'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='birth_date',
        # ),
    ]
