# Generated by Django 4.2.6 on 2023-12-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
