# Generated by Django 4.2.6 on 2023-12-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='birth_date',
        # ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=114, null=True, verbose_name='Описание'),
        ),
    ]
