# Generated by Django 4.2.6 on 2023-12-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='birth_date',
        # ),
    ]
