# Generated by Django 4.2.6 on 2023-12-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
    ]
